basecrm/urls.py
from django.contrib import admin
from django.urls import path, include

from trade.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trade.urls')),
]

handler404 = pageNotFound

trade/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('сlients/', сlients, name='сlients'),
    path('goods/', goods, name='goods'),
    path('employees/', employees, name='employees'),
    path('сlient/<slug:client_slug>/', show_сlient, name='сlient'),
    path('reports_salary/', reports_salary, name='reports_salary'),
    path('reports_salary_manage/', reports_salary_manage, name='reports_salary_manage'),
    path('reports_salary_managers_сomparison/', reports_salary_managers_сomparison, name='reports_salary_managers_сomparison'),
    path('reports_currencies/', reports_currencies, name='reports_currencies'),
    path('reports_currencies_uah/', reports_currencies_uah, name='reports_currencies_uah'),
    path('notes/', NotesList.as_view(), name='notes'),
    path('show_note/<int:note_id>/', show_note, name='show_note'),
    path('add_note/', AddNote.as_view(), name='add_note'),
    path('delete_note/<int:note_id>/', delete_note, name='delete_note'),


]

trade/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Notes(models.Model):
    title = models.CharField(max_length=255)
    date_change = models.DateTimeField(auto_now=True)
    content = models.TextField(blank=True)
    favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('show_note', kwargs={'note_id': self.pk})

    class Meta:
        ordering = ['id']

class Currencies(models.Model):
    code = models.CharField(max_length=3, db_index=True, primary_key=True)
    name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class ExchangeRates(models.Model):
    currencie = models.ForeignKey('Currencies', on_delete=models.PROTECT)
    date = models.DateField()
    value = models.DecimalField('value', null=False,max_digits=10, decimal_places=5,default=0)
    multiplicity = models.IntegerField()

    class Meta:
        indexes = [
            models.Index(fields=['-date'])
        ]

trade/forms.py
from datetime import datetime

from django import forms
from setuptools.msvc import winreg

from .models import *


class DateInput(forms.DateInput):
    input_type = 'date'


class ClientForm(forms.Form):
    guid = forms.CharField(max_length=50, required=False, label="Идентификатор")
    code = forms.CharField(max_length=20, label="Номер", widget=forms.TextInput(
        attrs={'class': 'form-control', 'readonly': 'readonly', 'class': 'form-control-plaintext'}))
    name = forms.CharField(max_length=250, label="Наименование",
                           widget=forms.TextInput(attrs={'class': 'form-control'}))
    full_name = forms.CharField(max_length=250, label="Полное наименование",
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    physical_address = forms.CharField(max_length=250, label="Физический адрес",
                                       widget=forms.TextInput(attrs={'class': 'form-control'}))
    legal_address = forms.CharField(max_length=250, label="Юридический адрес",
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))
    phones = forms.CharField(max_length=250, label="Телефоны", required=False,
                             widget=forms.Textarea(attrs={'cols': 10, 'rows': 3, 'class': 'form-control'}))
    vat_number = forms.CharField(max_length=20, required=False, label="ИНН",
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    comment = forms.CharField(widget=forms.Textarea(attrs={'cols': 10, 'rows': 4, 'class': 'form-control'}),
                              required=False, label="Комментарий")


class ReportForm(forms.Form):
    date_start = forms.DateField(widget=DateInput)
    date_end = forms.DateField(widget=DateInput)

    def __init__(self, *args, **kwargs):
        list_param1 = kwargs.pop('listparam1', None)
        super(ReportForm, self).__init__(*args, **kwargs)
        if list_param1:
            self.fields['listparam1'] = forms.CharField(label='Валюта',
                                                        widget=forms.Select(choices=list_param1))


class NoteForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'cols': 210, 'rows': 23, 'class': 'form-control'})
        }
        labels = {
            'title': 'Заголовок'
        }

trade/views.py
from django.http import HttpResponse, HttpResponseNotFound
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

import datetime
import requests
import json
from requests.auth import HTTPBasicAuth
import urllib.parse
from html import unescape

from .forms import *
from .models import *
from .utils import *
from django.shortcuts import render
from django.template import loader
from django.db.models import Q

from .report_utils import *


menu_directory = [{'title': 'Контрагенты', 'ref': 'сlients'}, {'title': 'Номенклатура', 'ref': 'goods'},
                  {'title': 'Торговые', 'ref': 'employees'}]
menu_documents = ["Продажи", "Оплаты", "Возвраты"]
menu_reports = [{'title': 'Продажи', 'ref': 'reports_salary'},
                {'title': 'Оплаты', 'ref': 'reports_salary'},
                {'title': 'Взаиморасчеты', 'ref': 'reports_salary'},
                {'title': 'Валюты', 'ref': 'reports_currencies'}
                ]


def index(request):
    return render(request, 'trade/index.html',
                  {'menu_directory': menu_directory, 'menu_documents': menu_documents, 'menu_reports': menu_reports})


def сlients(request):
    param_goods = {}
    headers = {'Accept': 'application/json'}
    name_method = "clients"
    url = 'http://localhost/CRM/hs/getClients/' + name_method + "/" + json.dumps(param_goods)
    response = requests.get(url, auth=HTTPBasicAuth('Admin', '123'), headers=headers)
    response.encoding = 'utf-8-sig'
    data = json.loads(response.text)

    return render(request, 'trade/clients.html',
                  {'menu_directory': menu_directory, 'menu_documents': menu_documents, 'menu_reports': menu_reports,
                   'datalist': data})


def goods(request):
    param_goods = {'sender': 'Alice', 'receiver': 'Bob', 'message': 'We did it!'}
    headers = {'Accept': 'application/json'}
    name_method = "goods"
    url = 'http://localhost/CRM/hs/getData/' + name_method + "/" + json.dumps(param_goods)
    response = requests.get(url, auth=HTTPBasicAuth('Admin', '123'), headers=headers)
    response.encoding = 'utf-8-sig'
    data = json.loads(response.text)

    return render(request, 'trade/goods.html',
                  {'menu_directory': menu_directory, 'menu_documents': menu_documents, 'menu_reports': menu_reports,
                   'datalist': data})


def employees(request):
    param_goods = {}
    headers = {'Accept': 'application/json'}
    name_method = "employees"
    url = 'http://localhost/CRM/hs/getData/' + name_method + "/" + json.dumps(param_goods)
    response = requests.get(url, auth=HTTPBasicAuth('Admin', '123'), headers=headers)
    response.encoding = 'utf-8-sig'
    data = json.loads(response.text)

    return render(request, 'trade/employees.html',
                  {'menu_directory': menu_directory, 'menu_documents': menu_documents, 'menu_reports': menu_reports,
                   'datalist': data})


def pageNotFound(request, exeption):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


def show_сlient(request, client_slug):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            form.cleaned_data["guid"] = client_slug
            # urllib.parse.quote_plus
            headers = {'Accept': 'application/json', 'Content-type': 'text/plain; charset=utf-8'}
            name_method = "update_client"

            url = 'http://localhost/CRM/hs/getData/' + name_method + "/" + json.dumps(form.cleaned_data,
                                                                                      ensure_ascii=False)
            response = requests.get(url, auth=HTTPBasicAuth('Admin', '123'), headers=headers)
            response.encoding = 'utf-8-sig'
            print(response.status_code)
    else:
        headers = {'Accept': 'application/json'}
        name_method = "get_client"
        url = 'http://localhost/CRM/hs/getData/' + name_method + "/" + client_slug
        response = requests.get(url, auth=HTTPBasicAuth('Admin', '123'), headers=headers)
        response.encoding = 'utf-8-sig'
        data = json.loads(response.text)

        form = ClientForm()
        form.fields["guid"].initial = data.get('GUID')
        form.fields["code"].initial = data.get('Code')
        form.fields["name"].initial = data.get('Name')
        form.fields["full_name"].initial = data.get('FullName')
        form.fields["physical_address"].initial = data.get('PhysicalAddress')
        form.fields["legal_address"].initial = data.get('LegalAddress')
        form.fields["phones"].initial = data.get('Phones')
        form.fields["vat_number"].initial = data.get('Phones')
        form.fields["comment"].initial = data.get('Comment')

    context = {
        'form': form,
        'slug': client_slug,
    }
    c_def = DataMixin.get_menu_context()
    context = dict(list(context.items()) + list(c_def.items()))
    return render(request, 'trade/client.html', context)


def reports_salary(request):
    context = DataMixin.get_menu_context()
    return render(request, 'trade/reports_salary.html', context)


def reports_currencies(request):
    context = DataMixin.get_menu_context()
    return render(request, 'trade/reports_currencies.html', context)


def reports_salary_manage(request):
    managers = {}
    percents = {}
    colors = {}
    total = 0
    if request.method == 'POST':
        form = ReportForm(request.POST)
        if form.is_valid():
            headers = {'Accept': 'application/json', 'Content-type': 'text/plain; charset=utf-8'}
            name_method = "reports_salary_manage"
            params = {'date_start': form.cleaned_data.get('date_start').strftime("%Y%m%d"),
                      'date_end': form.cleaned_data.get('date_end').strftime("%Y%m%d")}

            url = 'http://localhost/CRM/hs/getData/' + name_method + "/" + json.dumps(params, ensure_ascii=False)
            response = requests.get(url, auth=HTTPBasicAuth('Admin', '123'), headers=headers)
            response.encoding = 'utf-8-sig'
            data = json.loads(response.text)

            managers = data[0].get('Manager')
            percents = data[0].get('Percent')
            colors = get_colors(len(managers))
            total = data[0].get('Total')

    else:
        form = ReportForm()

    context = {
        'form': form,
        'managers': managers,
        'percents': percents,
        'colors': colors,
        'total': total,
    }
    c_def = DataMixin.get_menu_context()
    context = dict(list(context.items()) + list(c_def.items()))
    return render(request, 'trade/reports_salary_manage.html', context)


def reports_currencies_uah(request):
    currencies_list = [
        ('840', 'USD'),
        ('981', 'RUB'),
        ('978', 'EUR'),
        ('949', 'TRY'),
    ]

    dates = []
    rates = []
    if request.method == 'POST':
        form = ReportForm(request.POST, listparam1=currencies_list)
        if form.is_valid():
            check_load_exchange_rates_currencie()
            start_date = form.cleaned_data.get('date_start')
            end_date = form.cleaned_data.get('date_end')
            currency_id = form.cleaned_data.get('listparam1')
            rs_rates = ExchangeRates.objects.filter(currencie_id=currency_id, date__range=(start_date, end_date))
            for x in rs_rates:
                dates.append(x.date.strftime("%Y-%m-%d"))
                rates.append(str(x.value))
            print(currencies_list[0][0])

    else:
        form = ReportForm(listparam1=currencies_list)

    context = {
        'form': form,
        'dates': dates,
        'rates': rates
    }
    c_def = DataMixin.get_menu_context()
    context = dict(list(context.items()) + list(c_def.items()))
    return render(request, 'trade/reports_currencies_uah.html', context)


class NotesList(DataMixin, ListView):
    paginate_by = 15
    template_name = 'trade/notes.html'

    def get_queryset(self, **kwargs):
        params = self.request.GET.get('query', None)
        if params is None:
            return Notes.objects.all()
        else:
            return Notes.objects.filter(
                Q(content__icontains=params)
            )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        params = self.request.GET.get('query', None)
        if params is not None:
            context['search'] = params
        else:
            context['search'] = ''

        c_def = self.get_user_context()
        return dict(list(context.items()) + list(c_def.items()))


def show_note(request, note_id):
    note = get_object_or_404(Notes, pk=note_id)
    print(request.method)
    if request.method == 'POST':
        form = NoteForm(request.POST, instance=note)
        if form.is_valid():
            try:
                form.save()
                return redirect()
            except:
                form.add_error(None, 'Ошибка добавления заметки')
    else:
        form = NoteForm(instance=note)

    context = {
        'note_id': note_id,
        'form': form,
    }
    c_def = DataMixin.get_menu_context()
    context = dict(list(context.items()) + list(c_def.items()))

    return render(request, 'trade/note.html', context)


class AddNote(DataMixin, CreateView):
    form_class = NoteForm
    template_name = 'trade/add_note.html'
    success_url = reverse_lazy('notes')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context()
        return dict(list(context.items()) + list(c_def.items()))

def delete_note(request, note_id):
    try:
        instance = Notes.objects.get(id=note_id)
        instance.delete()
        return redirect('notes')
    except:
        print('Ошибка удаления заметки')
    return render(request)


def reports_salary_managers_сomparison(request):

trade/templates/trade/add_note.html
{% extends 'trade/base.html' %}

{% block content %}
<h5>Новая заметка</h5>
<form  action="{% url 'add_note' %}" method="post">
    {% csrf_token %}



    <div class="form-group col-md-11">
    <label for="{{ form.title.id_for_label }}">{{form.title.label}}</label>
      {{ form.title }}
  </div>

       <div class="form-group col-md-11">

      {{ form.content }}
  </div>

 <div class="col-auto">
    <button type="submit" class="btn btn-primary mb-3">Добавить</button>
  </div>


</form>

{% endblock%}

trade/templates/trade/client.html
{% extends 'trade/base.html' %}

{% block content %}

<h6>Контрагент</h6>
<form action="" method="post">
    {% csrf_token %}

  <div class="form-group col-md-2">
    <label for="{{ form.code.id_for_label }}">{{form.code.label}}</label>
      {{ form.code }}
  </div>
  <div class="form-group col-md-8">
    <label for="{{ form.name.id_for_label }}">{{form.name.label}}</label>
      {{ form.name }}
  </div>
  <div class="form-group col-md-8">
    <label for="{{ form.full_name.id_for_label }}">{{form.full_name.label}}</label>
      {{ form.full_name }}
  </div>
   <div class="form-group col-md-2">
    <label for="{{ form.vat_number.id_for_label }}">{{form.vat_number.label}}</label>
      {{ form.vat_number }}
  </div>

  <div class="form-group col-md-8">
    <label for="{{ form.legal_address.id_for_label }}">{{form.legal_address.label}}</label>
      {{ form.legal_address }}
  </div>

  <div class="form-group col-md-8">
    <label for="{{ form.physical_address.id_for_label }}">{{form.physical_address.label}}</label>
      {{ form.physical_address }}
  </div>

  <div class="form-group col-md-8">
    <label for="{{ form.phones.id_for_label }}">{{form.phones.label}}</label>
      {{ form.phones }}
  </div>

    <div class="form-group col-md-10">
    <label for="{{ form.comment.id_for_label }}">{{form.comment.label}}</label>
      {{ form.comment }}
  </div>
  <br>
  <button type="submit" class="btn btn-primary">Сохранить</button>
</form>

{% endblock%}

trade/templates/trade/clients.html
{% extends 'trade/base.html' %}

{% block content %}
 <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
                <th scope="col">Код</th>
              <th scope="col">Наименование</th>
              <th scope="col">Наименование полное</th>
              <th scope="col">Адрес</th>
            </tr>
          </thead>
          <tbody>

              {% for m in datalist %}
              <tr>
              <td><a href="{% url 'сlient' m.GUID %}">{{m.Code}} </a></td>
              <td>{{m.Name}}</td>
              <td>{{m.FullName}}</td>
              <td>{{m.Adress}}</td>
            </tr>
              {% endfor %}


          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


 {% endblock%}

trade/templates/trade/employees.html
{% extends 'trade/base.html' %}

{% block content %}
 <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Код</th>
              <th scope="col">Наименование</th>
            </tr>
          </thead>
          <tbody>
              {% for m in datalist %}
              <tr>
              <td>{{m.Code}}</td>
              <td>{{m.Name}}</td>
            </tr>
              {% endfor %}


          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


 {% endblock%}

trade/templates/trade/goods.html
{% extends 'trade/base.html' %}

{% block content %}
 <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Код</th>
              <th scope="col">Наименование</th>
            </tr>
          </thead>
          <tbody>
              {% for m in datalist %}
              <tr>
              <td>{{m.Code}}</td>
              <td>{{m.Name}}</td>
            </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


 {% endblock%}

trade/templates/trade/index.html
{% extends 'trade/base.html' %}

{% block content %}
<h1>{{title}}</h1>
<p>Главная страница
 {% endblock%}

trade/templates/trade/note.html
{% extends 'trade/base.html' %}

{% block content %}

<form action="{% url 'show_note' note_id %}" method="post">
    {% csrf_token %}

    <div class="form-group col-md-11">
        <label for="{{ form.title.id_for_label }}">{{form.title.label}}</label>
        {{ form.title }}
    </div>

    <div class="form-group col-md-11">

        {{ form.content }}
    </div>


    <div class="col-auto">
        <button type="submit" class="btn btn-primary mb-3">Сохранить</button>
        <button type="button" class="btn btn-danger mb-3" data-bs-toggle="modal" data-bs-target="#exampleModalCenter">
            Удалить
        </button>

        </button>

    </div>


</form>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Удалить запись?</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-footer">
                <form action="{% url 'delete_note' note_id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-secondary">Ok</button>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock%}

trade/templates/trade/notes.html
{% extends 'trade/base.html' %}

{% block content %}

<h6>Заметки</h6>

<form>

  <div class="form-group row">
<div class="col-10">
    <a href="{% url 'add_note' %}">Новая заметка </a>
     </div>

      <div class="col-2">
        <input value="{{ search }}" type="text" class="form-control" id="search" placeholder="поиск" >
     </div>

  </div>
</form>



 <div class="table-responsive">
        <table class="table table-striped table-sm">

          <tbody>

              {% for m in notes_list %}
              <tr>
                  <td> <a href="{% url 'show_note' m.id %}">{{m.title}} </a></td>
     </tr>
              {% endfor %}
          </tbody>
        </table>
      </div>
    </main>

{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">

      {% if page_obj.has_previous %}
      <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
      {% endif %}
      {% for p in paginator.page_range %}

      {% if page_obj.number == p %}
      <li class="page-item active">
      <span class="page-link">
        {{ p }}
        <span class="sr-only">(current)</span>
      </span>
    </li>
      {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
      <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
      {% endif %}

      {% endfor %}
      {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
      {% endif %}
  </ul>
</nav>
{% endif %}

  </div>




</div>

<script>
var input = document.getElementById("search");
input.addEventListener("keypress", function(event) {
  if (event.key === "Enter") {
    event.preventDefault();

      var x = document.getElementById("search").value;
  if (x == ""){
   location.href = 'http://127.0.0.1:8000'+{% url 'notes' %};
   }
  else{
   location.href = 'http://127.0.0.1:8000'+{% url 'notes' %} +'?query='+x;
   }

  }
});
</script>



{% endblock%}

trade/templates/trade/reports_currencies.html
{% extends 'trade/base.html' %}

{% block content %}

<div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Наименование</th>
              <th scope="col">Описание</th>
            </tr>
          </thead>
          <tbody>

              <tr>
              <td><a href="{% url 'reports_currencies_uah'  %}">UAH (гривна) курс валют </a></td>
              <td>UAH (гривна) курс валют</td>
            </tr>


          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


{% endblock%}

trade/templates/trade/reports_currencies_uah.html
{% extends 'trade/base.html' %}

{% block content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>

<form class="row g-3" action="" method="post">
    {% csrf_token %}
  <div class="col-auto">
    <label  class="visually-hidden">Период с</label>
    {{ form.date_start }}
  </div>
  <div class="col-auto">
    <label class="visually-hidden">по</label>
    {{ form.date_end }}
  </div>

  <div class="col-auto">
   {{ form.listparam1 }}
  </div>
  <div class="col-auto">
    <button type="submit" class="btn btn-primary mb-2">Сформировать</button>
  </div>

  <canvas id="line-chart" width="50" height="20"></canvas>

</form>

{% autoescape off %}
<script>
 const DATA_COUNT = 7;
 const NUMBER_CFG = {count: DATA_COUNT, min: 0, max: 100};


new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: {{ dates }} ,
    datasets: [{
        data: {{rates}} ,

        borderColor: "#3e95cd",
        fill: false
      }
    ]
  },
 options: {
    responsive: true,
     legend: {
      display: false
    },
    plugins: {
      title: {
        text: 'Chart.js Time Scale',
        display: true
      }
    },
    scales: {
      x: {
        type: 'time',
        time: {
          // Luxon format string
          tooltipFormat: 'DD T'
        },
        title: {
          display: true,
          text: 'Date'
        }
      },
      y: {
        title: {
          display: true,
          text: 'value'
        }
      }
    },
  },
});
</script>
{% endautoescape %}
{% endblock %}

trade/templates/trade/reports_salary.html
{% extends 'trade/base.html' %}

{% block content %}

<div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">Наименование</th>
              <th scope="col">Описание</th>
            </tr>
          </thead>
          <tbody>

              <tr>
              <td><a href="{% url 'reports_salary_manage'  %}">Доли продажи по менеджерам</a></td>
              <td>Доли продажи по менеджерам</td>
            </tr>
            <tr>
              <td><a href="{% url 'reports_salary_managers_сomparison'  %}">Сравнение продаж по менеджерам</a></td>
              <td>Сравнение продаж по менеджерам</td>
            </tr>

          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>


{% endblock%}

trade/templates/trade/reports_salary_manage.html
{% extends 'trade/base.html' %}

{% block content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@0.7.0"></script>

<form class="row g-3" action="" method="post">
    {% csrf_token %}
  <div class="col-auto">
    <label  class="visually-hidden">Период с</label>
    {{ form.date_start }}
  </div>
  <div class="col-auto">
    <label class="visually-hidden">по</label>
    {{ form.date_end }}
  </div>
  <div class="col-auto">
    <button type="submit" class="btn btn-primary mb-2">Сформировать</button>
  </div>
</form>


{% if managers|length  > 0 %}
   <canvas id="myChart" style="width:60%;"></canvas>
{% else %}
<p class="text-success">Нет данных для отображения, попробуйте изменить параметры</p>
{% endif %}



{% autoescape off %}
<script>
var xValues = {{ managers }};
var yValues = {{ percents }};
var barColors = {{ colors }};
const ctx = document.getElementById('myChart');



new Chart(ctx, {
  type: "pie",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    tooltips: {
    enabled: true
    },
    responsive: false,
    maintainAspectRatio: true,
    title: {
      display: true,
      text: "Доли продаж по менеджерам/торговым"
    },
    plugins: {
    datalabels: {
      formatter: (value, ctx) => {

        let sum = ctx.dataset._meta[0].total;
        let percentage = (value * 100 / sum).toFixed(0) + "%";
        return percentage;


      },
      color: '#fff',
    }
  }
  }
});
</script>
{% endautoescape %}
{% endblock%}